require('dotenv').config();

const settings = {
  packname: 'sᴛᴀʀ xᴅ',
  author: 'ᴍᴀʟᴠɪɴ ᴋɪɴɢ',
  botName: 'sᴛᴀʀ xᴅ', //Your bot name
  version: '1.2.0',
  botOwner: 'ᴍᴀʟᴠɪɴ ᴋɪɴɢ', //yobby mnare
  imageUrl: 'https://i.ibb.co/rRg9wTZV/malvin-xd.jpg',    
  ownerNumber: process.env.OWNER_NUMBER || '254708563093',
  giphyApiKey: process.env.GIPHY_API_KEY || 'qnl7ssQChTdPjsKta2Ax2LMaGXz303tq',
  commandMode: 'public',
  description: 'This is a bot for managing group commands and automating tasks.',
  AUTO_STATUS_SEEN: process.env.AUTO_STATUS_SEEN || 'true', // Automatically view WhatsApp statuses
  AUTO_STATUS_REACT: process.env.AUTO_STATUS_REACT || 'true', // Automatically react to WhatsApp statuses with random emoji
    
  SESSION_ID: process.env.SESSION_ID || 'starcore~eyJub2lzZUtleSI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoia0F6amxJam9VNDNnbnQxcTByWHgyMDlCZm1lNmNmMUloZDdCb3RRMmgybz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiK0RQVlBlVnA2ZTMwV1JiMVladU5rdGFnRmRuaGxtQ0k0MElDMERKNnFuVT0ifX0sInBhaXJpbmdFcGhlbWVyYWxLZXlQYWlyIjp7InByaXZhdGUiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJVUGkrc3RyQmxjK25FcDB6RkVZY2JLR25JQmdwK1pGZzVnNzRXK1JMZEhRPSJ9LCJwdWJsaWMiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJsb1lwQkcvdFR4RS8yYUEvelVjUzQwWGp0NjdhUGcrUTMvVmVWdlJjcnk0PSJ9fSwic2lnbmVkSWRlbnRpdHlLZXkiOnsicHJpdmF0ZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6ImFDK3BTbFNhS1pLUEF1NStud0UvVkJ2czdPQkJmRnR0eHhuemxvU2tjVnM9In0sInB1YmxpYyI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6Ikg2ZFF6aUdGYXhWcEVRVGo1MjVuR3dCc2YwaC9xeFVwZFZtRSt5bHJ1eFE9In19LCJzaWduZWRQcmVLZXkiOnsia2V5UGFpciI6eyJwcml2YXRlIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiUUxRMzZHRk95TVBTZFV6R2xrZ1Qwd0ZKREt2QkFObnZmelFaa3AvWlFXdz0ifSwicHVibGljIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiRk9kRU5qSUdBbEtDTXl1dmwwY2hSbExwTitsLyt6cFp6Q2ZtOUcyODlnOD0ifX0sInNpZ25hdHVyZSI6eyJ0eXBlIjoiQnVmZmVyIiwiZGF0YSI6IjRrMkM3S09vWml3UU12RVZOUE1yTkxwTXM1TjVObUYvb0hMQzlaaEtSWmFDMlBoR0dtNm10YnAwcFQxMXpaeTJVUWdyQ0pGOE81dlhKUWRlNE1Hb2pRPT0ifSwia2V5SWQiOjF9LCJyZWdpc3RyYXRpb25JZCI6MjAwLCJhZHZTZWNyZXRLZXkiOiJyR0ZXUXQ1QmFKd1BVQitGRjFSVFkzL21FZ0FvZy9RSWFJVGpObHNoeFQwPSIsInByb2Nlc3NlZEhpc3RvcnlNZXNzYWdlcyI6W10sIm5leHRQcmVLZXlJZCI6MzEsImZpcnN0VW51cGxvYWRlZFByZUtleUlkIjozMSwiYWNjb3VudFN5bmNDb3VudGVyIjowLCJhY2NvdW50U2V0dGluZ3MiOnsidW5hcmNoaXZlQ2hhdHMiOmZhbHNlfSwicmVnaXN0ZXJlZCI6dHJ1ZSwicGFpcmluZ0NvZGUiOiJTQUQ4NkVNMSIsIm1lIjp7ImlkIjoiMjU0NzA4NTYzMDkzOjZAcy53aGF0c2FwcC5uZXQiLCJsaWQiOiI3OTE3NDA2NDcyNjIzMzo2QGxpZCJ9LCJhY2NvdW50Ijp7ImRldGFpbHMiOiJDTnpHMStVRkVLT01nY1lHR0FFZ0FDZ0EiLCJhY2NvdW50U2lnbmF0dXJlS2V5IjoibitNbk54TXRiTGdvTThBcVkyNW12Zlg1UTBjdTFEcllxeDFpSDlqZ095RT0iLCJhY2NvdW50U2lnbmF0dXJlIjoiVUNaODZMb3N2REN2OFFmU2MyNUoraEtNRUkvbERZNHdibUdiYUJRVk1mVVV6b1phZUpQNWp5WWZkb3h3TXBmeWJXdzAzNGNBTTBkeW5qdzk5OVJWQ2c9PSIsImRldmljZVNpZ25hdHVyZSI6IlZCWUFSTE1lUnNSS29OOHBXcXJReEJVVmJUVWxybnVZZTNiTWdESVR1WVdBOEdoMklaQXJMNWZUdlZrbUtnNDAwREQ5K2tzcGJ5UXRKVFZUTmU4dGd3PT0ifSwic2lnbmFsSWRlbnRpdGllcyI6W3siaWRlbnRpZmllciI6eyJuYW1lIjoiMjU0NzA4NTYzMDkzOjZAcy53aGF0c2FwcC5uZXQiLCJkZXZpY2VJZCI6MH0sImlkZW50aWZpZXJLZXkiOnsidHlwZSI6IkJ1ZmZlciIsImRhdGEiOiJCWi9qSnpjVExXeTRLRFBBS21OdVpyMzErVU5ITHRRNjJLc2RZaC9ZNERzaCJ9fV0sInBsYXRmb3JtIjoiYW5kcm9pZCIsInJvdXRpbmdJbmZvIjp7InR5cGUiOiJCdWZmZXIiLCJkYXRhIjoiQ0FJSUJRPT0ifSwibGFzdEFjY291bnRTeW5jVGltZXN0YW1wIjoxNzU3NDMxMzQ2LCJsYXN0UHJvcEhhc2giOiIzUjlaMzkiLCJteUFwcFN0YXRlS2V5SWQiOiJBQUFBQU1lMSJ9'// make sure it starts with starecore~
};

global.SESSION_ID = settings.SESSION_ID;

module.exports = settings;
